- hosts: all
  become: true

  handlers:
  - name: "restart nginx"
    service:
      name: nginx
      state: restarted
    become: yes

  tasks:
    - name: "Roda: sudo apt update"
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #Um dia
    
    - name: "Instala pacotes em lote"
      apt:
        name: "{{ item }}"
        state: latest
      become: yes # roda com sudo
      with_items:
        - default-jdk
        - maven

    - name: "clone projeto"
      ansible.builtin.git:
        repo: 'https://github.com/Didox/spring-app-validar-cpf-treinamento-concrete'
        dest: /home/ubuntu/spring-app-validar-cpf-treinamento-concrete
        clone: yes
        update: yes

    - name: "fazendo build do projeto"
      shell: "cd spring-app-validar-cpf-treinamento-concrete && nohup mvn spring-boot:start &"
    
    - name: "Trocando nginx para VPS"
      copy:
        src: "nginx/default"
        dest: "/etc/nginx/sites-available/default"
      become: yes
      notify:
        - "restart nginx"